name: ePortfolio-front build-and-deploy

on: 
  push:
    paths:
      - '.github/workflows/front-build-deploy.yml'
      - 'front/**'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: install
      working-directory: 'front'
      run: npm ci

    - name: test
      working-directory: 'front'
      run: npm test

    - name: build
      working-directory: 'front'
      run: npm run build
      
    - name: remote add Heroku
      env:
        HEROKU_API_TOKEN: ${{ secrets.FRONT_HEROKU_API_TOKEN }}
        HEROKU_APP_NAME: "kotaro7750-e-portfolio-front"
      run: git remote add heroku-front https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
    
    - name: Deploy to Heroku
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: |
        git push heroku-front `git subtree split --prefix front master`:master --force
